import type { ComponentStyleConfig } from '@chakra-ui/theme'

export const Container: ComponentStyleConfig = {
  variants: {
    registration: {
      m: 0,
      maxW: 'none',
      w: '100%',
      h: '100%',
      color: 'black',
      bgColor: 'main',
    },
    header: {
      display: 'flex',
      w: '100%',
      maxW: 'none',
      px: 5,
      justifyContent: 'space-between',
      bgColor: 'main',
    },
    task: {
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'space-between',
      boxShadow: '0px 16px 50px 10px rgba(166, 164, 164, 0.2)',
      p: 10,
      m:1,
      w: 'md',
      minH: 72,
      bg: 'white',
      border: '1px solid',
      borderRadius: 10,
      borderColor: 'black',
    },
    task_done: {
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'space-between',
      boxShadow: '0px 16px 50px 10px rgba(166, 164, 164, 0.2)',
      p: 10,
      m:1,
      w: 'md',
      minH: 72,
      bg: 'main',
      borderRadius: 10,
    },
    task_description: {
      m: 0,
      p: 0,
    },
    task_tag: {
      borderRadius: 5,
      textAlign: 'center',
      w: 'auto',
      m:1,
      px:2,
      py:1,
      bgColor: 'main',
      color: 'black',
    },
    default: {
      m: 0,
      p: 0,
      maxW: 'none',
      border: '0px dashed transparent',
    },
  },
  defaultProps: {
    variant: 'default',
  },
}
